name: generate

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate
        run: make

      - name: Count changes
        id: changes
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Error Code
          delete-branch: true
          title: Update Error Code
          body: |
            Error codes have been updated.

            - https://github.com/postgres/postgres/blob/master/src/backend/utils/errcodes.txt
        if: steps.changes.outcome == 'failure'
